services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: flame
      POSTGRES_PASSWORD: flame
      POSTGRES_DB: flame
    ports:
      - "5432:5432"
    volumes:
      - flame-db:/var/lib/postgresql/data

volumes:
  flame-db:
